import fs from 'fs';
import path from 'path';
import { ServerConfig, TemplateDefinition, RenderContext } from '../types.js';
import { TEMPLATES } from '../templates/index.js';

/**
 * Generate an MCP server based on the provided configuration
 *
 * @param config - Server configuration from user input
 * @param targetDir - Target directory for the generated files
 */
export async function generateServer(config: ServerConfig, targetDir: string): Promise<void> {
  const template = getTemplate(config.template);

  // Create render context with project-specific values
  const context: RenderContext = {
    projectName: config.name,
    description: `MCP Server - ${config.name}`,
    serverType: config.serverType,
    hasTools: config.template === 'tools',
    hasLogging: config.features.includes('logging'),
    hasValidation: config.features.includes('validation'),
    isTypeScript: config.features.includes('typescript') || true, // Always include TS by default
    author: 'Generated by mcp-generator',
    version: '1.0.0',
  };

  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Generate all template files
  for (const file of template.files) {
    await writeFile(file, targetDir, context);
  }

  // Create additional directories based on features
  if (context.hasTools) {
    const toolsDir = path.join(targetDir, 'src', 'tools');
    if (!fs.existsSync(toolsDir)) {
      fs.mkdirSync(toolsDir, { recursive: true });
    }
  }

  if (context.hasLogging) {
    const utilsDir = path.join(targetDir, 'src', 'utils');
    if (!fs.existsSync(utilsDir)) {
      fs.mkdirSync(utilsDir, { recursive: true });
    }
  }
}

/**
 * Get template definition by type
 */
function getTemplate(templateType: string): TemplateDefinition {
  const template = TEMPLATES[templateType];
  if (!template) {
    throw new Error(`Unknown template: ${templateType}. Use 'basic' or 'tools'.`);
  }
  return template;
}

/**
 * Write a template file to the target directory
 */
async function writeFile(
  file: { path: string; content: string; isBinary?: boolean },
  targetDir: string,
  context: RenderContext
): Promise<void> {
  const filePath = path.join(targetDir, file.path);
  const dirPath = path.dirname(filePath);

  // Create directory if it doesn't exist
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  // Render template content if not binary
  let content = file.content;
  if (!file.isBinary) {
    content = renderTemplate(content, context);
  }

  // Write file
  fs.writeFileSync(filePath, content);
}

/**
 * Render template by replacing placeholders with actual values
 * Simple string replacement for common patterns
 */
function renderTemplate(content: string, context: RenderContext): string {
  return content
    .replace(/{{projectName}}/g, context.projectName)
    .replace(/{{description}}/g, context.description)
    .replace(/{{serverType}}/g, context.serverType)
    .replace(/{{hasTools}}/g, String(context.hasTools))
    .replace(/{{hasLogging}}/g, String(context.hasLogging))
    .replace(/{{hasValidation}}/g, String(context.hasValidation))
    .replace(/{{isTypeScript}}/g, String(context.isTypeScript))
    .replace(/{{author}}/g, context.author)
    .replace(/{{version}}/g, context.version);
}
